Gather

In [32]:
# Importing the required libraries :
import pandas as pd
import numpy as np
import requests
import os
import tweepy
import time
import json
import re
import itertools
import time
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Gather File -> twitter-archive-enchanced.csv

In [33]:
# Read the twitter_archive_enhanced.csv file which is stored in the porject folder
twitter_archive = pd.read_csv("twitter-archive-enhanced.csv", sep="," )
twitter_archive.head(2)

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0  892420643555336193                    NaN                  NaN   
1  892177421306343426                    NaN                  NaN   

                   timestamp  \
0  2017-08-01 16:23:56 +0000   
1  2017-08-01 00:17:27 +0000   

                                                                               source  \
0  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                                                                 text  \
0                                                       This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU   
1  This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV   

   retweeted_status_id  retweeted_status_user_id retweeted_status_timestamp  \
0                  NaN                       NaN                        NaN   
1                  NaN                       NaN                        NaN   

                                                     expanded_urls  \
0  https://twitter.com/dog_rates/status/892420643555336193/photo/1   
1  https://twitter.com/dog_rates/status/892177421306343426/photo/1   

   rating_numerator  rating_denominator     name doggo floofer pupper puppo  
0                13                  10  Phineas  None    None   None  None  
1                13                  10    Tilly  None    None   None  None

Gather file -> image-predictions.tsv using url

In [34]:
# Download tweet image predictions provided by Udacity
tweet_image_prediction_url = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
response = requests.get(tweet_image_prediction_url)

In [35]:
# Save the image-predictions.tsv locally:
with open(os.path.join(os.getcwd(), 
         tweet_image_prediction_url.split('/')[-1]), mode='wb') as file:
    file.write(response.content)

In [36]:
# Import the predictions into DataFrame
image_predictions = pd.read_csv("image-predictions.tsv", sep="\t" )

Gather tweets data from Twitter API

In [37]:
#Fetch the tweets from the Twitter API
# authentication keys
consumer_key = 'eL2DeeOX1wX7HH0Ldu3Jy6qNT'
consumer_secret = '0QnVbYfZlYxzuJI4Mx9GDIEb8uiQJlLoMBCyDH4V1KvxeCt6tF'
access_token = '852228407140261893-0sCUBrO7a2lnroq6sFhcRqCnn3QdPsS'
access_secret = 'qcHOxjOfFmrBaTkNp0rFJLLCtfL0hSR2ytQGOWlUo05Zj'

In [38]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
#Create the list of ids for fetching the tweets
#Use the ids of twitter_archive DataFrame
list_of_ids_in_twittter_archive = twitter_archive['tweet_id'].tolist()

In [40]:
# Fetch all tweets from the twitter API using loop:
list_of_tweets = []
# Tweets which are not useful are saved in a list 
cant_find_tweets_for_those_ids = []
for each_id in list_of_ids_in_twittter_archive:   
    try:
        start = time.time()
        list_of_tweets.append(api.get_status(each_id))
        end = time.time()
        print(end - start)
    except Exception as e:
        cant_find_tweets_for_those_ids.append(each_id)
        print(str(each_id))

0.1779334545135498
0.16844606399536133
0.16751360893249512
0.19694185256958008
0.20322656631469727
0.17343401908874512
0.16757416725158691
0.2596127986907959
0.18889117240905762
0.17571330070495605
0.1694016456604004
0.17273640632629395
0.16713881492614746
0.19635581970214844
0.1742544174194336
0.1765298843383789
0.16849541664123535
0.18430590629577637
0.16853046417236328
888202515573088257
0.18601250648498535
0.17920279502868652
0.2063584327697754
0.17048072814941406
0.17329025268554688
0.1917107105255127
0.17514538764953613
0.22866320610046387
0.16923236846923828
0.17304348945617676
0.21948742866516113
0.17502999305725098
0.19035053253173828
0.18187570571899414
0.1863095760345459
0.18194866180419922
0.1779797077178955
0.1752760410308838
0.1976175308227539
0.16774821281433105
0.17686867713928223
0.17339301109313965
0.3808598518371582
0.2082526683807373
0.16738104820251465
0.20182538032531738
0.1695418357849121
0.18388652801513672
0.1800534725189209
0.22054314613342285
0.17480278015136

0.18380260467529297
0.17403769493103027
0.17730379104614258
0.200056791305542
0.17263126373291016
0.18114089965820312
0.1742556095123291
0.18198156356811523
0.17203307151794434
0.16775298118591309
0.3110170364379883
0.18653154373168945
0.17285895347595215
0.17265939712524414
0.17423534393310547
0.19347763061523438
0.1910548210144043
0.16882586479187012
0.17151713371276855
0.18851375579833984
0.17737579345703125
0.218977689743042
0.16531610488891602
0.18863868713378906
0.16982007026672363
0.18106937408447266
0.18790030479431152
0.1863999366760254
0.1729443073272705
0.16898059844970703
0.16697978973388672
0.2533571720123291
0.22549080848693848
0.18222308158874512
0.1776731014251709
0.17853331565856934
0.16871213912963867
0.17314743995666504
0.20482921600341797
0.16776466369628906
0.18249869346618652
0.16656017303466797
0.18903112411499023
0.19241952896118164
0.17065024375915527
0.17784452438354492
0.18341660499572754
0.1769087314605713
0.1729717254638672
0.16959261894226074
0.18833541870

0.2066338062286377
0.17713451385498047
0.16658830642700195
0.17516875267028809
0.17980670928955078
0.18259644508361816
0.176513671875
0.1679527759552002
0.17933201789855957
0.1806812286376953
0.16564297676086426
0.17017269134521484
0.2009267807006836
0.18576884269714355
0.1744232177734375
0.17455673217773438
0.19458317756652832
0.17717504501342773
0.18305134773254395
0.16585159301757812
0.20626044273376465
0.18028616905212402
0.1715106964111328
0.19031167030334473
0.1836557388305664
0.19204974174499512
0.16492772102355957
0.18448305130004883
0.20590710639953613
0.1725144386291504
0.1789402961730957
0.1764049530029297
0.18517804145812988
0.1656506061553955
0.18448567390441895
0.2089076042175293
0.1851661205291748
0.16892027854919434
0.17877840995788574
0.16985321044921875
0.18199992179870605
0.17066097259521484
0.1837751865386963
0.1786186695098877
0.1815199851989746
0.16920185089111328
0.17647004127502441
0.18191051483154297
0.21526861190795898
0.17101049423217773
0.18059349060058594
0

0.22204875946044922
0.18068981170654297
0.17466020584106445
0.28885769844055176
0.2141883373260498
0.1706862449645996
0.17777562141418457
0.1827993392944336
0.1794426441192627
0.17029833793640137
0.19948196411132812
0.1943037509918213
0.18580865859985352
0.1681499481201172
0.17290544509887695
0.16619515419006348
0.21033215522766113
0.18214821815490723
0.17220711708068848
0.17333030700683594
0.20090484619140625
0.23266220092773438
0.1782548427581787
0.17110896110534668
0.194563627243042
0.17599725723266602
0.1942439079284668
0.20034265518188477
0.17890381813049316
0.18001985549926758
0.17297697067260742
0.17166996002197266
0.18201637268066406
0.17683076858520508
0.17512035369873047
0.17779183387756348
0.2042536735534668
0.18960094451904297
0.18894577026367188
0.1926884651184082
0.18117690086364746
0.18103480339050293
0.17164993286132812
0.22774171829223633
0.1844346523284912
0.17659330368041992
0.17393922805786133
0.16634464263916016
0.18166875839233398
0.17322731018066406
0.16981601715

0.21214079856872559
0.1920182704925537
0.1729435920715332
0.17756080627441406
0.1712205410003662
0.18949151039123535
0.18455147743225098
0.1733102798461914
0.19268798828125
0.17970776557922363
0.1685779094696045
0.18871045112609863
0.21455931663513184
0.18598341941833496
0.19292163848876953
0.1754460334777832
0.1736745834350586
0.18327808380126953
0.2190384864807129
0.1844775676727295
0.16997838020324707
0.18457841873168945
0.17537522315979004
0.18498682975769043
0.19057750701904297
0.2073659896850586
0.17458057403564453
0.17350125312805176
0.18697309494018555
0.18671011924743652
0.1659848690032959
0.18201661109924316
0.19594287872314453
0.2435152530670166
0.17142748832702637
0.17548847198486328
0.18217945098876953
0.1811354160308838
0.1679220199584961
0.1787407398223877
0.3847646713256836
0.1829366683959961
0.1787111759185791
0.17229318618774414
0.1773068904876709
0.19879746437072754
0.18902063369750977
0.17162466049194336
0.27100634574890137
0.17821764945983887
0.17044568061828613
0.

0.18838167190551758
0.17815446853637695
0.23294377326965332
0.18778514862060547
0.19479990005493164
0.17362499237060547
0.19617247581481934
0.16855669021606445
0.16967320442199707
0.1696453094482422
0.21646785736083984
0.2038402557373047
0.1763598918914795
0.16756653785705566
0.19014978408813477
0.17922687530517578
0.19054102897644043
0.17580199241638184
0.18791961669921875
0.17099976539611816
0.23263955116271973
0.19182991981506348
0.20288777351379395
0.18204569816589355
0.1725752353668213
0.18310070037841797
0.19353699684143066
0.18004226684570312
0.19771957397460938
0.17514657974243164
0.18608975410461426
0.17335152626037598
0.17260360717773438
0.20509052276611328
0.18488574028015137
0.1697545051574707
0.1712327003479004
0.17011117935180664
0.1970672607421875
0.17627596855163574
0.1695256233215332
0.1663811206817627
0.19266200065612793
0.17843008041381836
0.17798590660095215
0.18079400062561035
0.18574190139770508
0.1779639720916748
0.17820191383361816
0.17061161994934082
0.22481107

In [41]:
#Separate the json part of each tweepy status and add it to the list
my_list_of_dicts = []
for each_json_tweet in list_of_tweets:
    my_list_of_dicts.append(each_json_tweet._json)
#Write list to a txt file
with open('tweet_json.txt', 'w') as file:
        file.write(json.dumps(my_list_of_dicts, indent=4))

In [42]:
#Create DataFrame from the tweet_json.txt file:
my_demo_list = []
with open('tweet_json.txt', encoding='utf-8') as json_file:  
    all_data = json.load(json_file)
    for each_dictionary in all_data:
        tweet_id = each_dictionary['id']
        whole_tweet = each_dictionary['text']
        only_url = whole_tweet[whole_tweet.find('https'):]
        favorite_count = each_dictionary['favorite_count']
        retweet_count = each_dictionary['retweet_count'] 
        created_at = each_dictionary['created_at']
        whole_source = each_dictionary['source']
        only_device = whole_source[whole_source.find('rel="nofollow">') + 15:-4]
        source = only_device
        retweeted_status = each_dictionary['retweeted_status'] = each_dictionary.get('retweeted_status', 'Original tweet')
        if retweeted_status == 'Original tweet':
            url = only_url
        else:
            retweeted_status = 'This is a retweet'
            url = 'This is a retweet'
            
            my_demo_list.append({'tweet_id': str(tweet_id),
                             'favorite_count': int(favorite_count),
                             'retweet_count': int(retweet_count),
                             'url': url,
                             'created_at': created_at,
                             'source': source,
                             'retweeted_status': retweeted_status,
                            })
        tweet_json = pd.DataFrame(my_demo_list, columns = ['tweet_id', 'favorite_count', 
                                                       'retweet_count', 'created_at',
                                                       'source', 'retweeted_status', 'url'])


# Assess
# 1) twitter_archive

In [43]:
#Assess the twitter_archive dataframe
#Write the quality and tideness issues.
#Summarize the findings after completing visual and programatic assessment
#Arranging the data for better visualization
pd.options.display.max_colwidth = 10000
twitter_archive

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0     892420643555336193                    NaN                  NaN   
1     892177421306343426                    NaN                  NaN   
2     891815181378084864                    NaN                  NaN   
3     891689557279858688                    NaN                  NaN   
4     891327558926688256                    NaN                  NaN   
5     891087950875897856                    NaN                  NaN   
6     890971913173991426                    NaN                  NaN   
7     890729181411237888                    NaN                  NaN   
8     890609185150312448                    NaN                  NaN   
9     890240255349198849                    NaN                  NaN   
10    890006608113172480                    NaN                  NaN   
11    889880896479866881                    NaN                  NaN   
12    889665388333682689                    NaN                  NaN   
13    889638837579907072                    NaN                  NaN   
14    889531135344209921                    NaN                  NaN   
15    889278841981685760                    NaN                  NaN   
16    888917238123831296                    NaN                  NaN   
17    888804989199671297                    NaN                  NaN   
18    888554962724278272                    NaN                  NaN   
19    888202515573088257                    NaN                  NaN   
20    888078434458587136                    NaN                  NaN   
21    887705289381826560                    NaN                  NaN   
22    887517139158093824                    NaN                  NaN   
23    887473957103951883                    NaN                  NaN   
24    887343217045368832                    NaN                  NaN   
25    887101392804085760                    NaN                  NaN   
26    886983233522544640                    NaN                  NaN   
27    886736880519319552                    NaN                  NaN   
28    886680336477933568                    NaN                  NaN   
29    886366144734445568                    NaN                  NaN   
...                  ...                    ...                  ...   
2326  666411507551481857                    NaN                  NaN   
2327  666407126856765440                    NaN                  NaN   
2328  666396247373291520                    NaN                  NaN   
2329  666373753744588802                    NaN                  NaN   
2330  666362758909284353                    NaN                  NaN   
2331  666353288456101888                    NaN                  NaN   
2332  666345417576210432                    NaN                  NaN   
2333  666337882303524864                    NaN                  NaN   
2334  666293911632134144                    NaN                  NaN   
2335  666287406224695296                    NaN                  NaN   
2336  666273097616637952                    NaN                  NaN   
2337  666268910803644416                    NaN                  NaN   
2338  666104133288665088                    NaN                  NaN   
2339  666102155909144576                    NaN                  NaN   
2340  666099513787052032                    NaN                  NaN   
2341  666094000022159362                    NaN                  NaN   
2342  666082916733198337                    NaN                  NaN   
2343  666073100786774016                    NaN                  NaN   
2344  666071193221509120                    NaN                  NaN   
2345  666063827256086533                    NaN                  NaN   
2346  666058600524156928                    NaN                  NaN   
2347  666057090499244032                    NaN                  NaN   
2348  666055525042405380                    NaN                  NaN   
2349  666051853826850816                    NaN         

In [44]:
#Use the info method to assess the DataFrame
twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), ob

In [45]:
# There are missing records in the expanded_urls column. 
#They are replies since replies don't have url in the Twitter API
twitter_archive[twitter_archive['expanded_urls'].isnull()].loc[:,['expanded_urls', 
                                                                  'in_reply_to_status_id', 
                                                                  'in_reply_to_user_id',
                                                                 'retweeted_status_id']]


expanded_urls  in_reply_to_status_id  in_reply_to_user_id  \
30             NaN           8.862664e+17         2.281182e+09   
55             NaN           8.816070e+17         4.738443e+07   
64             NaN           8.795538e+17         3.105441e+09   
113            NaN           8.707262e+17         1.648776e+07   
148            NaN           8.634256e+17         7.759620e+07   
179            NaN           8.571567e+17         1.806710e+08   
185            NaN                    NaN                  NaN   
186            NaN           8.562860e+17         2.792810e+08   
188            NaN           8.558616e+17         1.943518e+08   
189            NaN           8.558585e+17         1.361572e+07   
218            NaN           8.503288e+17         2.195506e+07   
228            NaN           8.482121e+17         4.196984e+09   
234            NaN           8.476062e+17         4.196984e+09   
274            NaN           8.406983e+17         8.405479e+17   
290            NaN           8.381455e+17         2.195506e+07   
291            NaN           8.380855e+17         2.894131e+09   
313            NaN           8.352460e+17         2.625958e+07   
342            NaN           8.320875e+17         3.058208e+07   
346            NaN           8.319030e+17         2.068372e+07   
375            NaN                    NaN                  NaN   
387            NaN           8.265984e+17         4.196984e+09   
409            NaN           8.233264e+17         1.582854e+09   
427            NaN           8.211526e+17         1.132119e+08   
498            NaN           8.131273e+17         4.196984e+09   
513            NaN           8.116272e+17         4.196984e+09   
570            NaN           8.018543e+17         1.185634e+07   
576            NaN           8.008580e+17         2.918590e+08   
611            NaN           7.971238e+17         2.916630e+07   
701            NaN           7.727430e+17         7.305050e+17   
707            NaN                    NaN                  NaN   
843            NaN           7.667118e+17         4.196984e+09   
857            NaN           7.638652e+17         1.584641e+07   
967            NaN           7.501805e+17         4.717297e+09   
1005           NaN           7.476487e+17         4.196984e+09   
1080           NaN           7.384119e+17         3.589728e+08   
1295           NaN           7.079801e+17         2.319108e+09   
1345           NaN           7.044857e+17         2.878549e+07   
1445           NaN                    NaN                  NaN   
1446           NaN           6.964887e+17         4.196984e+09   
1474           NaN           6.936422e+17         4.196984e+09   
1479           NaN           6.935722e+17         1.198989e+09   
1497           NaN           6.924173e+17         4.196984e+09   
1523           NaN           6.903413e+17         4.670367e+08   
1598           NaN           6.860340e+17         4.196984e+09   
1605           NaN           6.855479e+17         4.196984e+09   
1618           NaN           6.849598e+17         4.196984e+09   
1663           NaN           6.827884e+17         4.196984e+09   
1689           NaN           6.813394e+17         4.196984e+09   
1774           NaN           6.780211e+17         4.196984e+09   
1819           NaN           6.765883e+17         4.196984e+09   
1844           NaN           6.758457e+17         4.196984e+09   
1895           NaN           6.747400e+17         4.196984e+09   
1905           NaN           6.744689e+17         4.196984e+09   
1914           NaN           6.658147e+17         1.637468e+07   
1940           NaN           6.737159e+17         4.196984e+09   
2038           NaN           6.715449e+17         4.196984e+09   
2149           NaN           6.693544e+17         4.196984e+09   
2189           NaN           6.689207e+17         2.143566e+07   
2298           NaN           6.670655e+17         4.196984e+09   

      retweeted_status_id  
30              

In [46]:
#Four non-url tweets are not replies. 
my_non_url_non_replies_ids = twitter_archive.iloc[[185, 375, 707, 1445],:].tweet_id
twitter_archive.iloc[[185, 375, 707, 1445],:]

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
185   856330835276025856                    NaN                  NaN   
375   828361771580813312                    NaN                  NaN   
707   785515384317313025                    NaN                  NaN   
1445  696518437233913856                    NaN                  NaN   

                      timestamp  \
185   2017-04-24 02:15:55 +0000   
375   2017-02-05 21:56:51 +0000   
707   2016-10-10 16:20:36 +0000   
1445  2016-02-08 02:18:30 +0000   

                                                                                  source  \
185   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
375                   <a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>   
707   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1445  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                          text  \
185   RT @Jenna_Marbles: @dog_rates Thanks for rating my cermets 14/10 wow I'm so proud I watered them so much   
375                                                  Beebop and Doobert should start a band 12/10 would listen   
707                                                             Today, 10/10, should be National Dog Rates Day   
1445                                                           Oh my god 10/10 for every little hot dog pupper   

      retweeted_status_id  retweeted_status_user_id  \
185          8.563302e+17                66699013.0   
375                   NaN                       NaN   
707                   NaN                       NaN   
1445                  NaN                       NaN   

     retweeted_status_timestamp expanded_urls  rating_numerator  \
185   2017-04-24 02:13:14 +0000           NaN                14   
375                         NaN           NaN                12   
707                         NaN           NaN                10   
1445                        NaN           NaN                10   

      rating_denominator  name doggo floofer  pupper puppo  
185                   10  None  None    None    None  None  
375                   10  None  None    None    None  None  
707                   10  None  None    None    None  None  
1445                  10  None  None    None  pupper  None

In [47]:
# Change dataype of tweet_id
twitter_archive['in_reply_to_status_id'].count() / len(twitter_archive)

0.033106960950764007

In [48]:
twitter_archive.shape

(2356, 17)

In [49]:
# Using the describe method
twitter_archive.describe()

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
count  2.356000e+03           7.800000e+01         7.800000e+01   
mean   7.427716e+17           7.455079e+17         2.014171e+16   
std    6.856705e+16           7.582492e+16         1.252797e+17   
min    6.660209e+17           6.658147e+17         1.185634e+07   
25%    6.783989e+17           6.757419e+17         3.086374e+08   
50%    7.196279e+17           7.038708e+17         4.196984e+09   
75%    7.993373e+17           8.257804e+17         4.196984e+09   
max    8.924206e+17           8.862664e+17         8.405479e+17   

       retweeted_status_id  retweeted_status_user_id  rating_numerator  \
count         1.810000e+02              1.810000e+02       2356.000000   
mean          7.720400e+17              1.241698e+16         13.126486   
std           6.236928e+16              9.599254e+16         45.876648   
min           6.661041e+17              7.832140e+05          0.000000   
25%           7.186315e+17              4.196984e+09         10.000000   
50%           7.804657e+17              4.196984e+09         11.000000   
75%           8.203146e+17              4.196984e+09         12.000000   
max           8.874740e+17              7.874618e+17       1776.000000   

       rating_denominator  
count         2356.000000  
mean            10.455433  
std              6.745237  
min              0.000000  
25%             10.000000  
50%             10.000000  
75%             10.000000  
max            170.000000

In [50]:
# Check rating numerators and denominators 
twitter_archive.nsmallest(10, 'rating_numerator')[['text', 'rating_numerator', 'rating_denominator']]

text  \
315                              When you're so blinded by your systematic plagiarism that you forget what day it is. 0/10 https://t.co/YbEJPkg4Ag   
1016                       PUPDATE: can't see any. Even if I could, I couldn't reach them to pet. 0/10 much disappointment https://t.co/c7WXaB2nqX   
605   RT @dog_rates: Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10 https://t.co/…   
1446                                         After reading the comments I may have overestimated this pup. Downgraded to a 1/10. Please forgive me   
1869                     What kind of person sends in a picture without a dog in it? 1/10 just because that's a nice table https://t.co/RDXCfk8hK0   
1940                                                      The millennials have spoken and we've decided to immediately demote to a 1/10. Thank you   
2038       After 22 minutes of careful deliberation this dog is being demoted to a 1/10. The longer you look at him the more terrifying he becomes   
2091      Flamboyant pup here. Probably poisonous. Won't eat kibble. Doesn't bark. Slow af. Petting doesn't look fun. 1/10 https://t.co/jxukeh2BeO   
2261  Never seen dog like this. Breathes heavy. Tilts head in a pattern. No bark. Shitty at fetch. Not even cordless. 1/10 https://t.co/i9iSGNn3fx   
2335      This is an Albanian 3 1/2 legged  Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv   

      rating_numerator  rating_denominator  
315                  0                  10  
1016                 0                  10  
605                  1                  10  
1446                 1                  10  
1869                 1                  10  
1940                 1                  10  
2038                 1                  10  
2091                 1                  10  
2261                 1                  10  
2335                 1                   2

In [51]:
twitter_archive.nlargest(10, 'rating_numerator')[['text', 'rating_numerator', 'rating_denominator']]

text  \
979                                                          This is Atticus. He's quite simply America af. 1776/10 https://t.co/GRXwMxLBkh   
313                                      @jonnysun @Lin_Manuel ok jomny I know you're excited but 960/00 isn't a valid rating, 13/10 is tho   
189   @s8n You tried very hard to portray this good boy as not so good, but you have ultimately failed. His goodness shines through. 666/10   
188                                                  @dhmontgomery We also gave snoop dogg a 420/10 but I think that predated your research   
2074                                                    After so many requests... here you go.\n\nGood dogg. 420/10 https://t.co/yfAAo1gdeY   
1120              Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once https://t.co/yGQI3He3xv   
290                                                                                                                      @markhoppus 182/10   
902                                                          Why does this never happen at my front door... 165/150 https://t.co/HmwrdfEfUE   
1779                                                                 IT'S PUPPERGEDDON. Total of 144/120 ...I think https://t.co/ZanVtAtvIq   
1634         Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you https://t.co/kRK51Y5ac3   

      rating_numerator  rating_denominator  
979               1776                  10  
313                960                   0  
189                666                  10  
188                420                  10  
2074               420                  10  
1120               204                 170  
290                182                  10  
902                165                 150  
1779               144                 120  
1634               143                 130

In [52]:
twitter_archive.nsmallest(10, 'rating_denominator')[['text', 'rating_numerator', 'rating_denominator']]

text  \
313                                                                          @jonnysun @Lin_Manuel ok jomny I know you're excited but 960/00 isn't a valid rating, 13/10 is tho   
2335                                   This is an Albanian 3 1/2 legged  Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv   
516   Meet Sam. She smiles 24/7 &amp; secretly aspires to be a reindeer. \nKeep Sam smiling by clicking and sharing this link:\nhttps://t.co/98tB8y7y7t https://t.co/LouL5vdvxx   
0                                                                 This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU   
1            This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV   
2                             This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB   
3                                                                       This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ   
4            This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f   
5            Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh   
6        Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n\nhttps://t.co/Zr4hWfAs1H https://t.co/tVJBRMnhxl   

      rating_numerator  rating_denominator  
313                960                   0  
2335                 1                   2  
516                 24                   7  
0                   13                  10  
1                   13                  10  
2                   12                  10  
3                   13                  10  
4                   12                  10  
5                   13                  10  
6                   13                  10

In [53]:
twitter_archive.nlargest(10, 'rating_denominator')[['text', 'rating_numerator', 'rating_denominator']]

text  \
1120                     Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once https://t.co/yGQI3He3xv   
902                                                                 Why does this never happen at my front door... 165/150 https://t.co/HmwrdfEfUE   
1634                Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you https://t.co/kRK51Y5ac3   
1779                                                                        IT'S PUPPERGEDDON. Total of 144/120 ...I think https://t.co/ZanVtAtvIq   
1635  Someone help the girl is being mugged. Several are distracting her while two steal her shoes. Clever puppers 121/110 https://t.co/1zfnTJLt55   
1228                                                 Happy Saturday here's 9 puppers on a bench. 99/90 good work everybody https://t.co/mpvaVxKmc1   
1254                                  Here's a brigade of puppers. All look very prepared for whatever happens next. 80/80 https://t.co/0eb7R1Om12   
1843                                   Here we have an entire platoon of puppers. Total score: 88/80 would pet all at once https://t.co/y93p6FLvVw   
433                                            The floofs have been released I repeat the floofs have been released. 84/70 https://t.co/NIYC820tmd   
1202                         This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 https://t.co/Kky1DPG4iq   

      rating_numerator  rating_denominator  
1120               204                 170  
902                165                 150  
1634               143                 130  
1779               144                 120  
1635               121                 110  
1228                99                  90  
1254                80                  80  
1843                88                  80  
433                 84                  70  
1202                50                  50

In [54]:
# In the above four DataFrames we can see that extreme ratings in the rating_numerator and rating_denominator 
# columns are largely in line with the twitter text, so our above hypothesis is not true. 
# But if we check i.e. the tweet in index 313 (the first tweet in the third DataFrame) or the tweet in 
# index 2335 (in the first DataFrame the last tweet), we can see that the first ratio found in text 
# was used to fill the rating numerator and denominator which is clearly not an optimal procedure as some 
# tweets seem to have more than one ratio in their body text. So we need to fix this.
# Using the sample method in order to identify any other remaining issues:
twitter_archive.sample(5)

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
1829  676237365392908289                    NaN                  NaN   
1285  708469915515297792                    NaN                  NaN   
292   838083903487373313                    NaN                  NaN   
369   828650029636317184                    NaN                  NaN   
1810  676821958043033607                    NaN                  NaN   

                      timestamp  \
1829  2015-12-14 03:08:46 +0000   
1285  2016-03-12 01:49:25 +0000   
292   2017-03-04 17:49:08 +0000   
369   2017-02-06 17:02:17 +0000   
1810  2015-12-15 17:51:44 +0000   

                                                                                  source  \
1829  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1285  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
292   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
369   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1810  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                                             text  \
1829     Say hello to Winston. He has no respect for the system. Much rebellion. I think that's a palm tree... nice. 8/10 https://t.co/dOLQddhXLZ   
1285         This is Bobble. He's a Croatian Galifianakis. Hears everything within 400 miles. 11/10 would snug diligently https://t.co/VwDc6PTDzk   
292   This is Daisy. She's puppears to be rare as all h*ck. Only seven like her currently domesticated. 13/10 pettable af https://t.co/meUc8jufAO   
369                                      Occasionally, we're sent fantastic stories. This is one of them. 14/10 for Grace https://t.co/bZ4axuH6OK   
1810                                                    Finally some constructive political change in this country. 11/10 https://t.co/mvQaETHVSb   

      retweeted_status_id  retweeted_status_user_id  \
1829                  NaN                       NaN   
1285                  NaN                       NaN   
292                   NaN                       NaN   
369                   NaN                       NaN   
1810                  NaN                       NaN   

     retweeted_status_timestamp  \
1829                        NaN   
1285                        NaN   
292                         NaN   
369                         NaN   
1810                        NaN   

                                                                                                                                                                                        expanded_urls  \
1829                                                                                                                                  https://twitter.com/dog_rates/status/676237365392908289/photo/1   
1285                                                                                                                                  https://twitter.com/dog_rates/status/708469915515297792/photo/1   
292                                                                   https://twitter.com/dog_rates/status/838083903487373313/photo/1,https://twitter.com/dog_rates/status/838083903487373313/photo/1   
369   https://twitter.com/dog_rates/status/828650029636317184/photo/1,https://twitter.com/dog_rates/status/828650029636317184/photo/1,https://twitter.com/dog_rates/status/828650029636317184/photo/1   
1810                                                                  https://twitter.com/dog_rates/status/676821958043033607/photo/1,https://twitter.com/dog_rates/status/676821958043033607/photo/1   

      rating_numerator  rating_denominator     name doggo floofer pupper puppo  
1829                 8                  10  Winston  None    None   None  None  
1285         

In [55]:
#Split the timestamp column in two columns: date and time. 
# Also the source column contains url followed by text, which needs to be cleaned
# Lastly, at the end of each tweet the url of the tweet is present and should be cleaned

Quality

twitter_archive table

1.Retweets present in the DataFrame (we only want original tweets with images)

2.Columns relevant to retweets needs to be dropped (we only want original tweets with images). Replies related columns not really needed.

3.Erroneous datatype for tweet_id

4.Erroneous rating_nominator and rating_denominator values

5.Clean the url from the tweet text

Tidiness

twitter_archive table

1.The expanded_urls column contains in some cells multiple urls that should be cleaned.

2.Source column data contains html code that should be cleaned.

3.Four variables (doggo, floofer, pupper, puppo) should be merged in one column

4.Timestamp should be split into date and time

# 2)image_predictions

In [56]:
# Visualizing image_predictions DataFrame and assessing it.
image_predictions

tweet_id  \
0     666020888022790149   
1     666029285002620928   
2     666033412701032449   
3     666044226329800704   
4     666049248165822465   
5     666050758794694657   
6     666051853826850816   
7     666055525042405380   
8     666057090499244032   
9     666058600524156928   
10    666063827256086533   
11    666071193221509120   
12    666073100786774016   
13    666082916733198337   
14    666094000022159362   
15    666099513787052032   
16    666102155909144576   
17    666104133288665088   
18    666268910803644416   
19    666273097616637952   
20    666287406224695296   
21    666293911632134144   
22    666337882303524864   
23    666345417576210432   
24    666353288456101888   
25    666362758909284353   
26    666373753744588802   
27    666396247373291520   
28    666407126856765440   
29    666411507551481857   
...                  ...   
2045  886366144734445568   
2046  886680336477933568   
2047  886736880519319552   
2048  886983233522544640   
2049  887101392804085760   
2050  887343217045368832   
2051  887473957103951883   
2052  887517139158093824   
2053  887705289381826560   
2054  888078434458587136   
2055  888202515573088257   
2056  888554962724278272   
2057  888804989199671297   
2058  888917238123831296   
2059  889278841981685760   
2060  889531135344209921   
2061  889638837579907072   
2062  889665388333682689   
2063  889880896479866881   
2064  890006608113172480   
2065  890240255349198849   
2066  890609185150312448   
2067  890729181411237888   
2068  890971913173991426   
2069  891087950875897856   
2070  891327558926688256   
2071  891689557279858688   
2072  891815181378084864   
2073  892177421306343426   
2074  892420643555336193   

                                                                                      jpg_url  \
0                                             https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg   
1                                             https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg   
2                                             https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg   
3                                             https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg   
4                                             https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg   
5                                             https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg   
6                                             https://pbs.twimg.com/media/CT5KoJ1WoAAJash.jpg   
7                                             https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg   
8                                             https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg   
9                                             https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg   
10                                            https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg   
11                                            https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg   
12                                            https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg   
13                                            https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg   
14                                            https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg   
15                                            https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg   
16                                            https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg   
17                                            https://pbs.twimg.com/media/CT56LSZWoAAlJj2.jpg   
18                                            https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg   
19                                            https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg   
20                                            https://pbs.twimg.com/media/CT8g3BpUEAAuFjg.jpg   
21                                            https://pbs.twimg.com/media/CT8mx7KW4AEQu8N.jpg   
22                                            ht

In [57]:
# Capitalize all breed names across columns
# Several columns have non descriptive names (p1, p1_conf, p1_dog, p2, 
# p2_conf, p2_dog, p3, p3_conf, p3_dog)
image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB


In [58]:
#Change tweet_id datatype.
image_predictions.describe()

tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [59]:
image_predictions.sample(5)

tweet_id  \
1543  791406955684368384   
1444  775733305207554048   
629   680913438424612864   
619   680440374763077632   
529   676811746707918848   

                                                                                      jpg_url  \
1543                                          https://pbs.twimg.com/media/CvukbEkWAAAV-69.jpg   
1444                                          https://pbs.twimg.com/media/CsP1UvaW8AExVSA.jpg   
629                                           https://pbs.twimg.com/media/CXMXKKHUMAA1QN3.jpg   
619   https://pbs.twimg.com/ext_tw_video_thumb/680440290977693696/pu/img/B900g7b-n-zhnwi5.jpg   
529                                           https://pbs.twimg.com/media/CWSEsO9WwAAX-fZ.jpg   

      img_num                  p1   p1_conf  p1_dog                p2  \
1543        4            Pembroke  0.972629    True          Cardigan   
1444        1  long-horned_beetle  0.613852   False                ox   
629         1          Pomeranian  0.615678    True  golden_retriever   
619         1        space_heater  0.920367   False          radiator   
529         1           Chihuahua  0.440916    True        Pomeranian   

       p2_conf  p2_dog                 p3   p3_conf  p3_dog  
1543  0.027026    True            basenji  0.000153    True  
1444  0.029473   False  rhinoceros_beetle  0.027806   False  
629   0.126455    True          Chihuahua  0.087184    True  
619   0.049933   False       electric_fan  0.006719   False  
529   0.345806    True     cocker_spaniel  0.060331    True

Quality

image_predictions table

1.Erroneous datatype for tweet_id.

2.Lowercase dog breed names

3.Non-descriptive column names for several variable

# 3)tweet_json

In [60]:
#check downloaded data from the Twitter API
tweet_json

tweet_id  favorite_count  retweet_count  \
0    886054160059072513               0            104   
1    885311592912609280               0          18595   
2    879130579576475649               0           6857   
3    878404777348136964               0           1299   
4    878316110768087041               0           6674   
5    877611172832227328               0             81   
6    874434818259525634               0          14866   
7    873337748698140672               0           1601   
8    871166179821445120               0           5770   
9    868639477480148993               0           2144   
10   867072653475098625               0            130   
11   866094527597207552               0           8616   
12   863471782782697472               0           2556   
13   860981674716409858               0           2245   
14   860924035999428608               0            846   
15   860177593139703809               0          32142   
16   858860390427611136               0           8481   
17   857062103051644929               0            178   
18   856602993587888130               0          11211   
19   856330835276025856               0            712   
20   855245323840757760               0           6303   
21   855138241867124737               0             48   
22   852936405516943360               0           2156   
23   851953902622658560               0          10300   
24   851861385021730816               0             23   
25   849668094696017920               0           5326   
26   847978865427394560               0           3508   
27   847971574464610304               0            463   
28   845098359547420673               0           8300   
29   841833993020538882               0          16736   
..                  ...             ...            ...   
138  776249906839351296               0          10220   
139  775898661951791106               0          17236   
140  773336787167145985               0           5673   
141  772615324260794368               0           3741   
142  771171053431250945               0           8398   
143  771004394259247104               0            245   
144  770093767776997377               0           3374   
145  769335591808995329               0           8520   
146  768909767477751808               0           3001   
147  768554158521745409               0           6462   
148  766864461642756096               0           6283   
149  766078092750233600               0           2873   
150  763167063695355904               0           3346   
151  761750502866649088               0           4372   
152  761371037149827077               0          19811   
153  760153949710192640               0             36   
154  759566828574212096               0          23390   
155  759159934323924993               0           1296   
156  757729163776290825               0           8952   
157  757597904299253760               0            322   
158  754874841593970688               0           8835   
159  753298634498793472               0           6366   
160  752701944171524096               0           3175   
161  752309394570878976               0          18358   
162  747242308580548608               0           3158   
163  746521445350707200               0           1075   
164  743835915802583040               0           2289   
165  711998809858043904               0            136   
166  667550904950915073               0             35   
167  667550882905632768               0             33   

                         created_at              source   retweeted_status  \
0    Sat Jul 15 02:45:48 +0000 2017  Twitter for iPhone  This is a retweet   
1    Thu Jul 13 01:35:06 +0000 2017  Twitter for iPhone  This is a retweet   
2    Mon Jun 26 00:13:58 +0000 2017  Twitter for iPhone  This is a retweet   
3    Sat Jun 24 00:09:53 +0000 2017  Twitter for iPhone  This is a retweet   
4    Fri Jun 23 18:17:33 +00

In [61]:
#Fetch the favorite_count and retweet_count columns
#add them to the twitter_archive DataFrame. So, we need to update the tidiness 
#issues of the twitter-archive table. We will also use the source column to update 
#the source column of the twitter-archive table. We have already documented the need 
#for cleaning the source column in the twitter-archive assessment.

In [62]:
# Check if retweets in the twitter-archive DataFrame are identified as
# retweets in the tweet_json DataFrame
tw_arch_retw = twitter_archive[twitter_archive['retweeted_status_id'].notnull()]['tweet_id'].tolist()
tweet_json_retw = tweet_json[tweet_json['retweeted_status'] == "This is a retweet" ]['tweet_id'].tolist()
tweet_json['retweeted_status'].value_counts()

This is a retweet    168
Name: retweeted_status, dtype: int64

In [63]:
# Checking datatypes of newly created lists:
print(type(tw_arch_retw[0]))
print(type(tweet_json_retw[0]))

<class 'int'>
<class 'str'>


In [64]:
# Converting list of strs to list of int in order to check for common elements
tweet_json_retw = list(map(int, tweet_json_retw))

In [65]:
# Count the number of common elements
len(list(set(tw_arch_retw).intersection(tweet_json_retw)))


168

In [66]:
len(tw_arch_retw)

181

In [67]:
#Use the retweeted_status_id column in the twitter-archive DataFrame
#to exclude retweets from the dataset
#7 retweets that weren't found in the Twitter API
#Find the urls of the fours tweets that wasn't replies:
tweet_json[tweet_json['tweet_id'].isin(list(map(str, my_non_url_non_replies_ids)))]

tweet_id  favorite_count  retweet_count  \
19  856330835276025856               0            712   

                        created_at              source   retweeted_status  \
19  Mon Apr 24 02:15:55 +0000 2017  Twitter for iPhone  This is a retweet   

                  url  
19  This is a retweet

In [68]:
# Not even in the Twitter API the urls of these tweets could be found
image_predictions[image_predictions['tweet_id'].isin(list(map(str, my_non_url_non_replies_ids)))]

Empty DataFrame
Columns: [tweet_id, jpg_url, img_num, p1, p1_conf, p1_dog, p2, p2_conf, p2_dog, p3, p3_conf, p3_dog]
Index: []

In [69]:
#No image predictions so drop all such datsets
tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 7 columns):
tweet_id            168 non-null object
favorite_count      168 non-null int64
retweet_count       168 non-null int64
created_at          168 non-null object
source              168 non-null object
retweeted_status    168 non-null object
url                 168 non-null object
dtypes: int64(2), object(5)
memory usage: 9.3+ KB


In [70]:
tweet_json.describe()

favorite_count  retweet_count
count           168.0     168.000000
mean              0.0    6824.357143
std               0.0    6493.905029
min               0.0      23.000000
25%               0.0    2606.000000
50%               0.0    5550.500000
75%               0.0    8544.000000
max               0.0   40835.000000

In [71]:
tweet_json.sample(5)

tweet_id  favorite_count  retweet_count  \
91   800443802682937345               0           4849   
153  760153949710192640               0             36   
7    873337748698140672               0           1601   
5    877611172832227328               0             81   
43   832769181346996225               0             41   

                         created_at              source   retweeted_status  \
91   Sun Nov 20 21:00:48 +0000 2016  Twitter for iPhone  This is a retweet   
153  Mon Aug 01 16:43:19 +0000 2016  Twitter for iPhone  This is a retweet   
7    Sat Jun 10 00:35:19 +0000 2017  Twitter for iPhone  This is a retweet   
5    Wed Jun 21 19:36:23 +0000 2017  Twitter for iPhone  This is a retweet   
43   Sat Feb 18 01:50:19 +0000 2017  Twitter for iPhone  This is a retweet   

                   url  
91   This is a retweet  
153  This is a retweet  
7    This is a retweet  
5    This is a retweet  
43   This is a retweet

Tidiness

twitter-archive table

Missing columns: favorite_count and retweet_count

To summarise the twitter_archive table has multiple quality and tidyness issue.

# Clean

Cleaning of the dataset starts here...

In [72]:
#Clean DataFrames based on the issues we found in 
#the assessment part of this wrangling project
#Firstly,make a copy of all 3 DataFrames:
twitter_archive_clean = twitter_archive.copy()
image_predictions_clean = image_predictions.copy()
tweet_json_clean = tweet_json.copy()

Quality issues

twitter-archive table

Retweets present in the dataset (we only want original tweets with images)

Define

Use the 'retweed_status_id' to drop retweets. Then use the 'tweet_id' from the image_predictions_clean DataFrame to keep only tweets with images.

Code

In [73]:
# Use separated retweed_status_id values in a list named as tw_arch_retw. 
# Use it to drop the rows containing retweets:
twitter_archive_clean = twitter_archive_clean[~twitter_archive_clean.tweet_id.isin(tw_arch_retw)]
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2175 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2175 non-null object
source                        2175 non-null object
text                          2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dtypes: float64(4), int64(3), object(1

In [74]:
# So we are left with 2175 original tweets. Now it's time to see which 
# of those tweets have image predictions in the image_prediction DataFrame.
# Separating image prediction ids
image_pred_ids = image_predictions_clean['tweet_id'].tolist()

In [75]:
# Seperating original tweet ids
twitter_archive_clean_ids = twitter_archive_clean['tweet_id'].tolist()

In [76]:
# Checking datatypes of newly created lists:
print(type(image_pred_ids[0]))
print(type(twitter_archive_clean_ids[0]))

<class 'int'>
<class 'int'>


In [77]:
# Count the number of common elements between the two lists:
print(len(list(set(image_pred_ids).intersection(twitter_archive_clean_ids))))

1994


In [78]:
# So there are 1994 original tweets that have image predictions.
# Saving the list of those tweets:
original_tweets_with_image_prediction_ids = list(set(image_pred_ids).intersection(twitter_archive_clean_ids))

In [79]:
# Keep only original tweets with image predictions
twitter_archive_clean = twitter_archive_clean[twitter_archive_clean.tweet_id.isin(original_tweets_with_image_prediction_ids)]

Test

In [80]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      1994 non-null int64
in_reply_to_status_id         23 non-null float64
in_reply_to_user_id           23 non-null float64
timestamp                     1994 non-null object
source                        1994 non-null object
text                          1994 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 1994 non-null object
rating_numerator              1994 non-null int64
rating_denominator            1994 non-null int64
name                          1994 non-null object
doggo                         1994 non-null object
floofer                       1994 non-null object
pupper                        1994 non-null object
puppo                         1994 non-null object
dtypes: float64(4), int64(3), object(1

Dropping Retweets (we only want original tweets with images). Replies related columns not really needed.

Define

Use pandas.DataFrame.drop to get rid of columns related to retweets and replies.

Test

In [81]:
twitter_archive_clean = twitter_archive_clean.drop(['retweeted_status_id', 
                                                    'retweeted_status_user_id', 
                                                    'retweeted_status_timestamp', 
                                                    'in_reply_to_status_id', 
                                                    'in_reply_to_user_id'],
                                                   axis=1)

In [82]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1994 non-null int64
timestamp             1994 non-null object
source                1994 non-null object
text                  1994 non-null object
expanded_urls         1994 non-null object
rating_numerator      1994 non-null int64
rating_denominator    1994 non-null int64
name                  1994 non-null object
doggo                 1994 non-null object
floofer               1994 non-null object
pupper                1994 non-null object
puppo                 1994 non-null object
dtypes: int64(3), object(9)
memory usage: 202.5+ KB


Erroneous datatype for tweet_id

Define

Convert 'tweed_id' column to string dataype

In [83]:
twitter_archive_clean['tweet_id'] = twitter_archive_clean['tweet_id'].astype('str')

Test

In [84]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1994 non-null object
timestamp             1994 non-null object
source                1994 non-null object
text                  1994 non-null object
expanded_urls         1994 non-null object
rating_numerator      1994 non-null int64
rating_denominator    1994 non-null int64
name                  1994 non-null object
doggo                 1994 non-null object
floofer               1994 non-null object
pupper                1994 non-null object
puppo                 1994 non-null object
dtypes: int64(2), object(10)
memory usage: 202.5+ KB


Erroneous rating_nominator and rating_denominator values

Define

Create a new column that stores all ratios found in the 'text' column. Use it to drop tweets containing more than one ratio.

Code

In [85]:
#Create a list of all ratings found in each tweet:
saved_ratios = []
for my_index in twitter_archive_clean.index.tolist():
    ratio = re.findall(r'\d+/\d+', twitter_archive_clean.loc[my_index, 'text'])
    saved_ratios.append(ratio)

In [86]:
# Adding the list to our DataFrame
twitter_archive_clean['rating'] = saved_ratios

In [87]:
# Fetching the indexes of tweets that have more than one rating: 
indexes_of_double_ratios = []
for my_index in twitter_archive_clean.index.tolist():
    if len(twitter_archive_clean.loc[my_index, 'rating']) > 1:
        indexes_of_double_ratios.append(my_index)

In [88]:
# Printing these tweets:
twitter_archive_clean.loc[indexes_of_double_ratios, 
                          ['text', 'rating_numerator', 'rating_denominator',
                          'url', 'rating']]

text  \
766                                   "Yep... just as I suspected. You're not flossing." 12/10 and 11/10 for the pup not flossing https://t.co/SuXcI9B7pQ   
1007                     This is Bookstore and Seaweed. Bookstore is tired and Seaweed is an asshole. 10/10 and 7/10 respectively https://t.co/eUGjGjjFVJ   
1068         After so many requests, this is Bretagne. She was the last surviving 9/11 search dog, and our second ever 14/10. RIP https://t.co/XAVDNDaVgQ   
1165                                                                                     Happy 4/20 from the squad! 13/10 for all https://t.co/eV1diwds8a   
1202                                This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 https://t.co/Kky1DPG4iq   
1222     Meet Travis and Flurp. Travis is pretty chill but Flurp can't lie down properly. 10/10 &amp; 8/10\nget it together Flurp https://t.co/Akzl5ynMmE   
1359               This is Socks. That water pup w the super legs just splashed him. Socks did not appreciate that. 9/10 and 2/10 https://t.co/8rc5I22bBf   
1459           This may be the greatest video I've ever been sent. 4/10 for Charles the puppy, 13/10 overall. (Vid by @stevenxx_) https://t.co/uaJmNgXR2P   
1465  Meet Oliviér. He takes killer selfies. Has a dog of his own. It leaps at random &amp; can't bark for shit. 10/10 &amp; 5/10 https://t.co/6NgsQJuSBJ   
1508     When bae says they can't go out but you see them with someone else that same night. 5/10 &amp; 10/10 for heartbroken pup https://t.co/aenk0KpoWM   
1525       This is Eriq. His friend just reminded him of last year's super bowl. Not cool friend\n10/10 for Eriq\n6/10 for friend https://t.co/PlEXTofdpf   
1538  Meet Fynn &amp; Taco. Fynn is an all-powerful leaf lord and Taco is in the wrong place at the wrong time. 11/10 &amp; 10/10 https://t.co/MuqHPvtL8c   
1662          This is Darrel. He just robbed a 7/11 and is in a high speed police chase. Was just spotted by the helicopter 10/10 https://t.co/7EsP8LmSp5   
1795    Meet Tassy &amp; Bee. Tassy is pretty chill, but Bee is convinced the Ruffles are haunted. 10/10 &amp; 11/10 respectively https://t.co/fgORpmTN9C   
1832            These two pups just met and have instantly bonded. Spectacular scene. Mesmerizing af. 10/10 and 7/10 for blue dog https://t.co/gwryaJO4tC   
1897     Meet Rufio. He is unaware of the pink legless pupper wrapped around him. Might want to get that checked 10/10 &amp; 4/10 https://t.co/KNfLnYPmYh   
1901        Two gorgeous dogs here. Little waddling dog is a rebel. Refuses to look at camera. Must be a preteen. 5/10 &amp; 8/10 https://t.co/YPfw7oahbD   
1970         Meet Eve. She's a raging alcoholic 8/10 (would b 11/10 but pupper alcoholism is a tragic issue that I can't condone) https://t.co/U36HYQIijg   
2010                                                      10/10 for dog. 7/10 for cat. 12/10 for human. Much skill. Would pet all https://t.co/uhx5gfpx5k   
2064      Meet Holly. She's trying to teach small human-like pup about blocks but he's not paying attention smh. 11/10 &amp; 8/10 https://t.co/RcksaUrGNu   
2113              Meet Hank and Sully. Hank is very proud of the pumpkin they found and Sully doesn't give a shit. 11/10 and 8/10 https://t.co/cwoP1ftbrj   
2177        Here we have Pancho and Peaches. Pancho is a Condoleezza Gryffindor, and Peaches is just an asshole. 10/10 &amp; 7/10 https://t.co/Lh1BsJrWPp   
2216     This is Spark. He's nervous. Other dog hasn't moved in a while. Won't come when called. Doesn't fetch well 8/10&amp;1/10 https://t.co/stEodX9Aba   
2263          This is Kial. Kial is either wearing a cape, which would be rad, or flashing us, which would be rude. 10/10 or 4/10 https://t.co/8zcwIoiuqR   
2272           Two dogs in this one. Both are rare Jujitsu Pythagoreans. One slightly whiter than other. Long legs. 7/10 and 8/10 https://t.co/ITxxcc4v9y   
2306     These are Peruvian Feldspars. Their names are Cupit and Pr

In [89]:
len(indexes_of_double_ratios)

27

In [90]:
# There are only 27 tweets that have more than 1 ratio in their text.
# Most often the reason for having more than one rating is that the 
# image attached to the tweet has more than 1 animal depicted 
# (usually a second dog).
# As a consequence the rating_numerator and rating_denominator columns
# contain only the first encountered ratio in the tweet text which is 
# clearly not optimal. We must notice that for few tweets the added ratio is 
# not related to dog ratings (i.e a date). 
# If we try to classify these ratios as 'dog rating' or 'not dog rating' 
# the only noticeable pattern in the tweets is this one: when a ratio is 
# followed by the word 'and' or '&amp;' then followed by another ratio, 
# then these two ratios most likely refer to dog ratings. 
# Even if we did that, we should check one by one the remaining tweets. 
# Moreover, the fact that we need to store the added ratings in a new column, 
# thus creating columns almost full of NaNs (as only 27 tweets out of 1994 have 
# more than one rating), further leads us to the decision to entirely drop these 
# 27 tweets and work only with tweets that have only one rating.
# Dropping double ratio tweeets:
twitter_archive_clean = twitter_archive_clean[~twitter_archive_clean.index.isin(indexes_of_double_ratios)]

In [91]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 13 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
expanded_urls         1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
rating                1967 non-null object
dtypes: int64(2), object(11)
memory usage: 215.1+ KB


In [92]:
# We are left with 1967 tweets. Now it's time to drop the 'rating' column 
# that we created as we dont need it anymore:
twitter_archive_clean = twitter_archive_clean.drop('rating', axis=1)

Test

In [93]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
expanded_urls         1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
dtypes: int64(2), object(10)
memory usage: 199.8+ KB


In [94]:
twitter_archive_clean.sample(5)

tweet_id                  timestamp  \
981   749417653287129088  2016-07-03 01:41:06 +0000   
1978  672984142909456390  2015-12-05 03:41:37 +0000   
1110  733822306246479872  2016-05-21 00:50:46 +0000   
1186  718540630683709445  2016-04-08 20:46:50 +0000   
650   792883833364439040  2016-10-31 00:20:11 +0000   

                                                                                  source  \
981   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1978  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1110  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1186  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
650   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                              text  \
981                                     This is Finn. He's the most unphotogenic pupper of all time. 11/10 https://t.co/qvA2rCUl6v   
1978      Very happy pup here. Always smiling. Loves his little leaf. Carries it everywhere with him. 9/10 https://t.co/81BCQAyvcs   
1110                       This is Moose. He's a Polynesian Floofer. Dapper af. 10/10 would pet diligently https://t.co/mVfqRdppTL   
1186                                                                 Get you a pup that can do both. 10/10 https://t.co/zSbyvm62xZ   
650   This is Bailey. She's rather h*ckin hype for Halloween tomorrow. Carved those pupkins herself. 12/10 https://t.co/v17mFm0Ftz   

                                                                                                                                                                                                                                                        expanded_urls  \
981   https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1   
1978                                                                                                                                                                                                  https://twitter.com/dog_rates/status/672984142909456390/photo/1   
1110                                                                                                                                                                                                  https://twitter.com/dog_rates/status/733822306246479872/photo/1   
1186                                                                                                                                  https://twitter.com/dog_rates/status/718540630683709445/photo/1,https://twitter.com/dog_rates/status/718540630683709445/photo/1   
650   https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1   

      rating_numerator  rating_denominator    name doggo  floofer  pupper  \
981                 11                  10    Finn  None     None  pupper   
1978                 9                  10    None  None     None    None   
1110                10                  10   Moose  None  floofer    None   
1186                10                  10    None  None     None    None   
650                 12                  10  Bailey  None     None    None   

     puppo  
981   None  
1978  None  
1110  None  
1186  None  
650   None

Clean the url from the tweet text

Define

Separate the url part of each tweet in the 'text' column and delete it.

Code

In [95]:
# This function takes as input a dataframe column, search for a specif word and deletes all text after it 
# including the word. The output is stored into a list.
def create_a_list_of_str_up_to_word(dataframe, column, word):
    my_list_of_texts = []
    for my_text in dataframe[column]:
        my_list_of_texts.append(my_text)
    all_cleaned_texts = []
    for my_text_2 in my_list_of_texts:
        cleaned_text = my_text_2[:my_text_2.find(word)-1]
        all_cleaned_texts.append(cleaned_text)
    return(all_cleaned_texts)

In [96]:
#Check the cleaned data
twitter_archive_clean['new_text'] = create_a_list_of_str_up_to_word(twitter_archive_clean, 'text', 'https')

In [97]:
twitter_archive_clean.loc[:, ['text', 'new_text']]

text  \
0                                                              This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU   
1         This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV   
2                          This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB   
3                                                                    This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ   
4         This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f   
5         Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh   
6     Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n\nhttps://t.co/Zr4hWfAs1H https://t.co/tVJBRMnhxl   
7                             When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10 https://t.co/v0nONBcwxq   
8                         This is Zoey. She doesn't want to be one of the scary sharks. Just wants to be a snuggly pettable boatpet. 13/10 #BarkWeek https://t.co/9TwLuAGH0b   
9              This is Cassie. She is a college pup. Studying international doggo communication and stick theory. 14/10 so elegant much sophisticate https://t.co/t1bfwz5S2A   
10                This is Koda. He is a South Australian deckshark. Deceptively deadly. Frighteningly majestic. 13/10 would risk a petting #BarkWeek https://t.co/dVPW0B0Mme   
11                                       This is Bruno. He is a service shark. Only gets out of the water to assist you. 13/10 terrifyingly good boy https://t.co/u1XPQMl29g   
12                                        Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10 https://t.co/BxvuXk0UCm   
13                                                       This is Ted. He does his best. Sometimes that's not enough. But it's ok. 12/10 would assist https://t.co/f8dEDcrKSR   
14                            This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek https://t.co/y70o6h3isq   
15        This is Oliver. You're witnessing one of his many brutal attacks. Seems to be playing with his victim. 13/10 fr*ckin frightening #BarkWeek https://t.co/WpHvrQedPb   
16                                                            This is Jim. He found a fren. Taught him how to sit like the good boys. 12/10 for both https://t.co/chxruIOUJN   
17                  This is Zeke. He has a new stick. Very proud of it. Would like you to throw it for him without taking it. 13/10 would do my best https://t.co/HTQ77yNQ5K   
18                                                           This is Ralphus. He's powering up. Attempting maximum borkdrive. 13/10 inspirational af https://t.co/YnYAFCTTiK   
20                   This is Gerald. He was just told he didn't get the job he interviewed for. A h*ckin injustice. 12/10 didn't want the job anyway https://t.co/DK7iDPfuRX   
21                   This is Jeffrey. He has a monopoly on the pool noodles. Currently running a 'boop for two' midweek sale. 13/10 h*ckin strategic https://t.co/PhrUk20Q64   
22                                      I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: roxy.thedoxy) https://t.co/20VrLAA8ba   
23                                               This is Canela. She attempted some fancy porch pics. They were unsucces

In [98]:
# Copying the 'new_text' column to the old one:
twitter_archive_clean['text'] = create_a_list_of_str_up_to_word(twitter_archive_clean, 'text', 'https')
twitter_archive_clean = twitter_archive_clean.drop(['new_text'], axis=1)

Test

In [99]:
twitter_archive_clean.sample(5)

tweet_id                  timestamp  \
663   790946055508652032  2016-10-25 16:00:09 +0000   
459   817827839487737858  2017-01-07 20:18:46 +0000   
1539  689661964914655233  2016-01-20 04:13:20 +0000   
2088  670792680469889025  2015-11-29 02:33:32 +0000   
43    884162670584377345  2017-07-09 21:29:42 +0000   

                                                                                  source  \
663   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
459   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1539  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
2088  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
43    <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                                              text  \
663                                                     This is Betty. She's assisting with the dishes. Such a good puppo. 12/10 h*ckin helpful af   
459                           This is Buddy. He ran into a glass door once. Now he's h*ckin skeptical. 13/10 empowering af (vid by Brittany Gaunt)   
1539                                                        Meet Luca. He's a Butternut Scooperfloof. Glorious tongue. 12/10 would pet really well   
2088                          This is Antony. He's a Sheraton Tetrahedron. Skips awkwardly. Doesn't look when he crosses the road (reckless). 7/10   
43    Meet Yogi. He doesn't have any important dog meetings today he just enjoys looking his best at all times. 12/10 for dangerously dapper doggo   

                                                        expanded_urls  \
663   https://twitter.com/dog_rates/status/790946055508652032/photo/1   
459   https://twitter.com/dog_rates/status/817827839487737858/video/1   
1539  https://twitter.com/dog_rates/status/689661964914655233/photo/1   
2088  https://twitter.com/dog_rates/status/670792680469889025/photo/1   
43    https://twitter.com/dog_rates/status/884162670584377345/photo/1   

      rating_numerator  rating_denominator    name  doggo floofer pupper  \
663                 12                  10   Betty   None    None   None   
459                 13                  10   Buddy   None    None   None   
1539                12                  10    Luca   None    None   None   
2088                 7                  10  Antony   None    None   None   
43                  12                  10    Yogi  doggo    None   None   

      puppo  
663   puppo  
459    None  
1539   None  
2088   None  
43     None

image_predictions table

Erroneous datatype for tweet_id.

Define

Convert 'tweed_id' column to string dataype.

Code

In [100]:
image_predictions_clean['tweet_id'] = image_predictions_clean['tweet_id'].astype('str')

Test

In [101]:
image_predictions_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null object
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(1), object(5)
memory usage: 152.1+ KB


Lowercase dog breed names

Define

Capitalize all words found in columns 'p1', 'p2' and 'p3'.

Code

In [102]:
image_predictions_clean['p1'] = image_predictions_clean['p2'].str.title()
image_predictions_clean['p2'] = image_predictions_clean['p2'].str.title()
image_predictions_clean['p3'] = image_predictions_clean['p3'].str.title()

Test

In [103]:
image_predictions_clean.loc[:,['p1', 'p2', 'p3']].sample(10)

p1               p2                  p3
1760  Shopping_Basket  Shopping_Basket           Mousetrap
1237       Guinea_Pig       Guinea_Pig            Cardigan
656        Eskimo_Dog       Eskimo_Dog            Malamute
1970   French_Bulldog   French_Bulldog             Printer
192       Toy_Terrier      Toy_Terrier  Miniature_Pinscher
253             Tabby            Tabby        Egyptian_Cat
860          Pembroke         Pembroke             Basenji
1975         Envelope         Envelope         Book_Jacket
1949              Pug              Pug               Boxer
364           Warthog          Warthog       Water_Buffalo

Non-descriptive column names for several variables.

Define

Change the title of non-descriptive columns to more appropriate ones

Code

In [104]:
image_predictions_clean = image_predictions_clean.rename(columns={'jpg_url': 'image_url',
                                                                  'img_num': 'image_number',
                                                                 'p1': 'top_prediction',
                                                                  'p1_conf': 'top_pred_conf',
                                                                  'p2': 'second_prediction',
                                                                  'p2_conf': 'second_pred_conf',
                                                                  'p3': 'third_prediction',
                                                                  'p3_conf': 'third_pred_conf',
                                                                  'p1_dog': 'is_dog_top_pred',
                                                                  'p2_dog': 'is_dog_sec_pred',
                                                                  'p3_dog': 'is_dog_third_pred',
                                                                 })

Test

In [105]:
image_predictions_clean.head()

tweet_id                                        image_url  \
0  666020888022790149  https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg   
1  666029285002620928  https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg   
2  666033412701032449  https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg   
3  666044226329800704  https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg   
4  666049248165822465  https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg   

   image_number      top_prediction  top_pred_conf  is_dog_top_pred  \
0             1              Collie       0.465074             True   
1             1  Miniature_Pinscher       0.506826             True   
2             1            Malinois       0.596461             True   
3             1             Redbone       0.408143             True   
4             1          Rottweiler       0.560311             True   

    second_prediction  second_pred_conf  is_dog_sec_pred     third_prediction  \
0              Collie          0.156665             True    Shetland_Sheepdog   
1  Miniature_Pinscher          0.074192             True  Rhodesian_Ridgeback   
2            Malinois          0.138584             True           Bloodhound   
3             Redbone          0.360687             True   Miniature_Pinscher   
4          Rottweiler          0.243682             True             Doberman   

   third_pred_conf  is_dog_third_pred  
0         0.061428               True  
1         0.072010               True  
2         0.116197               True  
3         0.222752               True  
4         0.154629               True

Tidiness issues

twitter_archive table

The expanded_urls column contain in some cells multiple urls that should be cleaned.

Define

Delete all urls and merge the url column of the tweet_json table to twitter_archive_table.

Code

In [106]:
twitter_archive_clean = twitter_archive_clean.drop('expanded_urls',axis=1)
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 11 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
dtypes: int64(2), object(9)
memory usage: 184.4+ KB


In [107]:
twitter_archive_clean = pd.merge(twitter_archive_clean, tweet_json_clean.loc[:, ['tweet_id','url']], 
                                  on='tweet_id', how='left')
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 12 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
url                   0 non-null object
dtypes: int64(2), object(10)
memory usage: 199.8+ KB


In [108]:
twitter_archive_clean.tail()

tweet_id                  timestamp  \
1962  666049248165822465  2015-11-16 00:24:50 +0000   
1963  666044226329800704  2015-11-16 00:04:52 +0000   
1964  666033412701032449  2015-11-15 23:21:54 +0000   
1965  666029285002620928  2015-11-15 23:05:30 +0000   
1966  666020888022790149  2015-11-15 22:32:08 +0000   

                                                                                  source  \
1962  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1963  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1964  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1965  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1966  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                     text  \
1962                     Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10   
1963    This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10   
1964           Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af   
1965  This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of   
1966          Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet   

      rating_numerator  rating_denominator  name doggo floofer pupper puppo  \
1962                 5                  10  None  None    None   None  None   
1963                 6                  10     a  None    None   None  None   
1964                 9                  10     a  None    None   None  None   
1965                 7                  10     a  None    None   None  None   
1966                 8                  10  None  None    None   None  None   

      url  
1962  NaN  
1963  NaN  
1964  NaN  
1965  NaN  
1966  NaN

In [109]:
# If we open the urls and check the text column we can see that we have correctly matched 
# the tweets with the appropriate urls. But if a tweet contains in it's text a url, 
# the url column would contain two https addresses which is clearly not what we want.
# So we will create a column that count https: 
twitter_archive_clean['count_https'] = twitter_archive_clean.url.str.count(r'https')

In [110]:
# So if a tweet has more than one http it must be cleaned:
twitter_archive_clean['count_https'].value_counts()

Series([], Name: count_https, dtype: int64)

In [111]:
# And lets print these tweets: # And le 
twitter_archive_clean[twitter_archive_clean['count_https'] == 2]

Empty DataFrame
Columns: [tweet_id, timestamp, source, text, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, url, count_https]
Index: []

In [112]:
# Two tweets with extra https.
# Remove first https because each tweet 
# url is always at the end of the twitter text
# This function finds the start-end index of a string in a pandas cell.
# It returns multiple indexes if the string is found more than once.
def start_end_index_of_string(dataframe, column, index, string):
    find_index_of_https = [(i.start(), i.end()) for i in re.finditer(
        string, dataframe.loc[index, column])]
    return find_index_of_https

In [113]:
# This function keeps only the last occurence of a selected
# string in a pandas cell and drops everything before it.
def keep_only_last_str_occurence(dataframe, column, index, string):
    my_cell = dataframe.loc[index, column]
    save_my_index = start_end_index_of_string(dataframe, column, index, string)   
    if len(save_my_index) > 1:
        dataframe.at[index, column] = my_cell[save_my_index[-1][0]:]
    else:
        pass

In [114]:
# Search which tweets has more one https in their ulr column 
# and save their index into a list:
index_of_tweets_with_more_than_one_url = twitter_archive_clean[
    twitter_archive_clean['count_https'] == 2].index

In [115]:
# Updating the  cells:
for my_index in index_of_tweets_with_more_than_one_url:
    keep_only_last_str_occurence(twitter_archive_clean, 'url', my_index, 'https')

In [116]:
# Checking the dataset for results
twitter_archive_clean[twitter_archive_clean['count_https'] == 2]

Empty DataFrame
Columns: [tweet_id, timestamp, source, text, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, url, count_https]
Index: []

Test

In [117]:
# Recounting https: 
twitter_archive_clean['count_https'] = twitter_archive_clean.url.str.count(r'https')
twitter_archive_clean['count_https'].value_counts()

Series([], Name: count_https, dtype: int64)

In [118]:
# Dropping the count_https column 
twitter_archive_clean = twitter_archive_clean.drop('count_https', axis=1)

In [119]:
twitter_archive_clean.loc[:, ['text', 'url']].sample(10)

text  \
420   This is Loki. He'll do your taxes for you. Can also make room in your budget for all the things you bought today. 12/10 what a puppo   
1561                                              When you realize it doesn't matter how hard you study. You're still going to fail. 10/10   
978                   Meet Karma. She's just a head. Lost body during the Second Punic War (unfortunate). Loves to travel 10/10 petable af   
96                          This is Dewey (pronounced "covfefe"). He's having a good walk. Arguably the best walk. 13/10 would snug softly   
1313                                                                                   aahhhhkslaldhwnxmzbbs 12/10 for being da smooshiest   
1528                                                      Everyone please just appreciate how perfect these two photos are. 12/10 for both   
1305                     This is Griffin. He's desperate for both a physical and emotion connection. 11/10 I'd hug the hell out of Griffin   
114      This is Meatball. He doing what's known in the industry as a mid-strut mlem. H*ckin fancy boy. 12/10 I'd do anything for Meatball   
1234                                                                                   With great pupper comes great responsibility. 12/10   
1185                                                   I present to you... Dog Jesus. 13/10 (he could be sitting on a rock but I doubt it)   

      url  
420   NaN  
1561  NaN  
978   NaN  
96    NaN  
1313  NaN  
1528  NaN  
1305  NaN  
114   NaN  
1234  NaN  
1185  NaN

Source column data contains html code that should be cleaned.

Define

Clean the 'source column' using the tweet_json_clean 'source' column.

Code

In [120]:
twitter_archive_clean = pd.merge(twitter_archive_clean, tweet_json_clean.loc[:, ['tweet_id','source']], 
                                  on='tweet_id', how='left')

In [121]:
twitter_archive_clean.head(5)

tweet_id                  timestamp  \
0  892420643555336193  2017-08-01 16:23:56 +0000   
1  892177421306343426  2017-08-01 00:17:27 +0000   
2  891815181378084864  2017-07-31 00:18:03 +0000   
3  891689557279858688  2017-07-30 15:58:51 +0000   
4  891327558926688256  2017-07-29 16:00:24 +0000   

                                                                             source_x  \
0  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
2  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
3  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
4  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                                                         text  \
0                                                       This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10   
1  This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10   
2                   This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10   
3                                                             This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us   
4  This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and should be respected as such. 12/10 #BarkWeek   

   rating_numerator  rating_denominator      name doggo floofer pupper puppo  \
0                13                  10   Phineas  None    None   None  None   
1                13                  10     Tilly  None    None   None  None   
2                12                  10    Archie  None    None   None  None   
3                13                  10     Darla  None    None   None  None   
4                12                  10  Franklin  None    None   None  None   

   url source_y  
0  NaN      NaN  
1  NaN      NaN  
2  NaN      NaN  
3  NaN      NaN  
4  NaN      NaN

In [122]:
twitter_archive_clean['source_x'].value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     1930
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       26
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source_x, dtype: int64

In [123]:
twitter_archive_clean['source_y'].value_counts()

Series([], Name: source_y, dtype: int64)

In [124]:
twitter_archive_clean[twitter_archive_clean['source_y'] == 'TweetDeck'].loc[:, ['source_x', 'source_y']]

Empty DataFrame
Columns: [source_x, source_y]
Index: []

In [125]:
twitter_archive_clean[twitter_archive_clean['source_y'] == 'Twitter Web Client'].loc[:, ['source_x', 'source_y']]

Empty DataFrame
Columns: [source_x, source_y]
Index: []

In [126]:
# So now let's drop the initial source column, keep the new one and renaming it
twitter_archive_clean = twitter_archive_clean.drop(['source_x'], axis=1)
twitter_archive_clean = twitter_archive_clean.rename(columns={'source_y': 'source'})

Test

In [127]:
twitter_archive_clean.sample(5)

tweet_id                  timestamp  \
534   780931614150983680  2016-09-28 00:46:20 +0000   
1627  672488522314567680  2015-12-03 18:52:12 +0000   
83    872620804844003328  2017-06-08 01:06:27 +0000   
1484  675781562965868544  2015-12-12 20:57:34 +0000   
709   750868782890057730  2016-07-07 01:47:22 +0000   

                                                                                                                      text  \
534           I want to finally rate this iconic puppo who thinks the parade is all for him. 13/10 would absolutely attend   
1627        This is Jackie. She was all ready to go out, but her friends just cancelled on her. 10/10 hang in there Jackie   
83    This is Monkey. She's supporting owners everywhere with her fancy #PrideMonth bandana. 13/10 love is love is love...   
1484                                                                Say hello to Buddah. He was Waldo for Halloween. 11/10   
709   Meet Milo. He hauled ass until he ran out of treadmill and then passed out from exhaustion. 11/10 sleep tight pupper   

      rating_numerator  rating_denominator    name doggo floofer  pupper  \
534                 13                  10    None  None    None    None   
1627                10                  10  Jackie  None    None    None   
83                  13                  10  Monkey  None    None    None   
1484                11                  10  Buddah  None    None    None   
709                 11                  10    Milo  None    None  pupper   

      puppo  url source  
534   puppo  NaN    NaN  
1627   None  NaN    NaN  
83     None  NaN    NaN  
1484   None  NaN    NaN  
709    None  NaN    NaN

Four variables (doggo, floofer, pupper, puppo) should be merged in one column

Define

Merge data of 'doggo', 'floofer', 'pupper', 'puppo' in one column.

Code

In [128]:
twitter_archive_clean['doggo'].replace('None', '', inplace=True)
twitter_archive_clean['floofer'].replace('None', '', inplace=True)
twitter_archive_clean['pupper'].replace('None', '', inplace=True)
twitter_archive_clean['puppo'].replace('None', '', inplace=True)

In [129]:
twitter_archive_clean['stage'] = (twitter_archive_clean['doggo'] + 
                                    twitter_archive_clean['floofer'] + 
                                    twitter_archive_clean['pupper'] + 
                                    twitter_archive_clean['puppo'])

In [130]:
twitter_archive_clean['stage'].replace('', 'unidentified', inplace=True)

In [131]:
twitter_archive_clean = twitter_archive_clean.drop(['doggo', 'floofer', 'pupper', 'puppo'], axis=1)

Test

In [132]:
# It seems that 11 dogs are identified belonging in two 'stages':
twitter_archive_clean['stage'].value_counts()

unidentified    1663
pupper           201
doggo             63
puppo             22
doggopupper        9
floofer            7
doggopuppo         1
doggofloofer       1
Name: stage, dtype: int64

In [133]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 9 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
dtypes: int64(2), object(7)
memory usage: 153.7+ KB


In [134]:
twitter_archive_clean.head()

tweet_id                  timestamp  \
0  892420643555336193  2017-08-01 16:23:56 +0000   
1  892177421306343426  2017-08-01 00:17:27 +0000   
2  891815181378084864  2017-07-31 00:18:03 +0000   
3  891689557279858688  2017-07-30 15:58:51 +0000   
4  891327558926688256  2017-07-29 16:00:24 +0000   

                                                                                                                                         text  \
0                                                       This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10   
1  This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10   
2                   This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10   
3                                                             This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us   
4  This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and should be respected as such. 12/10 #BarkWeek   

   rating_numerator  rating_denominator      name  url source         stage  
0                13                  10   Phineas  NaN    NaN  unidentified  
1                13                  10     Tilly  NaN    NaN  unidentified  
2                12                  10    Archie  NaN    NaN  unidentified  
3                13                  10     Darla  NaN    NaN  unidentified  
4                12                  10  Franklin  NaN    NaN  unidentified

Timestamp should be split into date and time

Define

Convert the 'timestamp' to datetime dataype and split it to date, time, and day of week.

Code

In [135]:
twitter_archive_clean['timestamp'] = pd.DatetimeIndex(twitter_archive_clean['timestamp'])

In [136]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 9 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null datetime64[ns]
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 153.7+ KB


In [137]:
temp = pd.DatetimeIndex(twitter_archive_clean['timestamp'])
twitter_archive_clean['Date'] = temp.date
twitter_archive_clean['Year'] = temp.year
twitter_archive_clean['Month'] = temp.month

In [138]:
twitter_archive_clean['Month'].replace(1, 'January', inplace=True)
twitter_archive_clean['Month'].replace(2, 'February', inplace=True)
twitter_archive_clean['Month'].replace(3, 'March', inplace=True)
twitter_archive_clean['Month'].replace(4, 'April', inplace=True)
twitter_archive_clean['Month'].replace(5, 'May', inplace=True)
twitter_archive_clean['Month'].replace(6, 'June', inplace=True)
twitter_archive_clean['Month'].replace(7, 'July', inplace=True)
twitter_archive_clean['Month'].replace(8, 'August', inplace=True)
twitter_archive_clean['Month'].replace(9, 'September', inplace=True)
twitter_archive_clean['Month'].replace(10, 'October', inplace=True)
twitter_archive_clean['Month'].replace(11, 'November', inplace=True)
twitter_archive_clean['Month'].replace(12, 'December', inplace=True)

In [139]:
twitter_archive_clean['Day_of_Week'] = temp.dayofweek
twitter_archive_clean['Day_of_Week'].replace(0, 'Monday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(1, 'Tuesday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(2, 'Wednesday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(3, 'Thursday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(4, 'Friday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(5, 'Saturday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(6, 'Sunday', inplace=True)

twitter_archive_clean['Time'] = temp.time

twitter_archive_clean['Hour'] = temp.hour

twitter_archive_clean = twitter_archive_clean.drop('timestamp', axis=1)


Test

In [140]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 14 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
dtypes: int64(4), object(10)
memory usage: 230.5+ KB


In [141]:
twitter_archive_clean.sample(5)

tweet_id  \
1270  685325112850124800   
499   787717603741622272   
1118  697881462549430272   
14    889531135344209921   
203   842163532590374912   

                                                                                                                                              text  \
1270                                                       "Tristan do not speak to me with that kind of tone or I will take away the Xbox." 10/10   
499                            This is Tonks. She is a service puppo. Can hear a caterpillar hiccup from 7 miles away. 13/10 would follow anywhere   
1118                                        This is Carter. He wakes up in the morning and pisses excellence. 10/10 best there is plain and simple   
14                          This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek   
203   Meet George. He looks slightly deflated but overall quite powerful. Not sure how that human restrained him. 12/10 would snug with permission   

      rating_numerator  rating_denominator    name  url source         stage  \
1270                10                  10    None  NaN    NaN  unidentified   
499                 13                  10   Tonks  NaN    NaN         puppo   
1118                10                  10  Carter  NaN    NaN  unidentified   
14                  13                  10  Stuart  NaN    NaN         puppo   
203                 12                  10  George  NaN    NaN  unidentified   

            Date  Year     Month Day_of_Week      Time  Hour  
1270  2016-01-08  2016   January      Friday  05:00:14     5  
499   2016-10-16  2016   October      Sunday  18:11:26    18  
1118  2016-02-11  2016  February    Thursday  20:34:41    20  
14    2017-07-24  2017      July      Monday  17:02:04    17  
203   2017-03-16  2017     March    Thursday  00:00:07     0

Missing columns: favorite_count and retweet_count

Define

Merge the 'favorite_count' and 'retweet_count' columns of tweet_jso_clean table to the twitter_archive_clean table.

Code

In [142]:
twitter_archive_clean = pd.merge(twitter_archive_clean, 
                                 tweet_json_clean.loc[:, ['tweet_id', 
                                'favorite_count','retweet_count']], 
                                  on='tweet_id', how='left')

Test

In [143]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 16 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
favorite_count        0 non-null float64
retweet_count         0 non-null float64
dtypes: float64(2), int64(4), object(10)
memory usage: 261.2+ KB


In [144]:
twitter_archive_clean.sample(5)

tweet_id  \
1782  669567591774625800   
1600  673213039743795200   
997   708109389455101952   
475   792394556390137856   
1487  675707330206547968   

                                                                                                                     text  \
1782  Meet Kollin. He's a Parakeetian Badminton from Denmark. Great artist. Taking break from research. Loves wicker 9/10   
1600                                                                     This is Dexter. He just got some big news. 10/10   
997         This is Remington. He was caught off guard by the magical floating cheese. Spooked af. 10/10 deep breaths pup   
475                    Meet BeBe. She rocks the messy bun of your dreams. H*ckin flawless. 12/10 would watch her tutorial   
1487                                                           We've got ourselves a battle here. Watch out Reggie. 11/10   

      rating_numerator  rating_denominator       name  url source  \
1782                 9                  10     Kollin  NaN    NaN   
1600                10                  10     Dexter  NaN    NaN   
997                 10                  10  Remington  NaN    NaN   
475                 12                  10       BeBe  NaN    NaN   
1487                11                  10       None  NaN    NaN   

             stage        Date  Year     Month Day_of_Week      Time  Hour  \
1782  unidentified  2015-11-25  2015  November   Wednesday  17:25:28    17   
1600  unidentified  2015-12-05  2015  December    Saturday  18:51:11    18   
997   unidentified  2016-03-11  2016     March      Friday  01:56:49     1   
475   unidentified  2016-10-29  2016   October    Saturday  15:55:58    15   
1487  unidentified  2015-12-12  2015  December    Saturday  16:02:36    16   

      favorite_count  retweet_count  
1782             NaN            NaN  
1600             NaN            NaN  
997              NaN            NaN  
475              NaN            NaN  
1487             NaN            NaN

Final cleaning step and Storing the data

Now it's time to create the master pandas DataFrame that we are going to store in a csv file. We will merge the twitter_archive_clean and the image_predictions_clean DataFrames into a single one:

In [145]:
twitter_archive_master = pd.merge(twitter_archive_clean, 
                                 image_predictions_clean.loc[:, ['tweet_id','image_url',
                                                                 'image_number', 'top_prediction', 
                                                                 'top_pred_conf', 'is_dog_top_pred', 
                                                                 'second_prediction', 'second_pred_conf',
                                                                 'is_dog_sec_pred', 'third_prediction', 
                                                                 'third_pred_conf', 'is_dog_third_pred']], 
                                  on='tweet_id', how='left')

In [146]:
twitter_archive_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 27 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
favorite_count        0 non-null float64
retweet_count         0 non-null float64
image_url             1967 non-null object
image_number          1967 non-null int64
top_prediction        1967 non-null object
top_pred_conf         1967 non-null float64
is_dog_top_pred       1967 non-null bool
second

In [147]:
twitter_archive_master.to_csv('twitter_archive_master.csv')

We will also save as csv files the 3 cleaned datasets (twitter_archive_clean, image_predictions_clean, tweet_json_clean) for future reference

In [148]:
twitter_archive_clean.to_csv('twitter_archive_clean.csv')
image_predictions_clean.to_csv('image_predictions_clean.csv')
tweet_json_clean.to_csv('tweet_json_clean.csv')

Data Analysis and Visualizations

Now it's time to use the cleaned master Dataframe to analyse the data and create relevant and interesting visualizations.

In [149]:
print(twitter_archive_master['Date'][-1:][len(twitter_archive_master)-1])
print(twitter_archive_master['Date'][0])
print((twitter_archive_master['Date'][0] - twitter_archive_master['Date'][-1:][1966]).days)

2015-11-15
2017-08-01
625


The dataset covers 625 days from 15 November of 2015 until 1 of August of 2017.

In [150]:
twitter_archive_master.describe()

rating_numerator  rating_denominator         Year         Hour  \
count       1967.000000         1967.000000  1967.000000  1967.000000   
mean          12.311134           10.517031  2015.851551     9.753940   
std           41.769700            7.310967     0.699750     8.619246   
min            0.000000            7.000000  2015.000000     0.000000   
25%           10.000000           10.000000  2015.000000     1.000000   
50%           11.000000           10.000000  2016.000000     4.000000   
75%           12.000000           10.000000  2016.000000    18.000000   
max         1776.000000          170.000000  2017.000000    23.000000   

       favorite_count  retweet_count  image_number  top_pred_conf  \
count             0.0            0.0   1967.000000    1967.000000   
mean              NaN            NaN      1.203355       0.593831   
std               NaN            NaN      0.561868       0.272192   
min               NaN            NaN      1.000000       0.044333   
25%               NaN            NaN      1.000000       0.360447   
50%               NaN            NaN      1.000000       0.587764   
75%               NaN            NaN      1.000000       0.844583   
max               NaN            NaN      4.000000       1.000000   

       second_pred_conf  third_pred_conf  
count      1.967000e+03     1.967000e+03  
mean       1.340996e-01     6.015671e-02  
std        1.005274e-01     5.066928e-02  
min        1.011300e-08     1.740170e-10  
25%        5.314460e-02     1.619495e-02  
50%        1.174020e-01     4.952370e-02  
75%        1.948820e-01     9.153815e-02  
max        4.880140e-01     2.710420e-01

The mean dog rating for the dataset is 12.3.

On average 8,959 twitter users favorite each WeRateDogs original tweet.

The mean retweet count is substantially lower: 2,771.

The most liked tweet was liked by 131,813 users.

The most retweeted tweet was retweeted 78,740 times.

Which were the most common dog ratings?

In [ ]:
twitter_archive_master['rating_numerator'].value_counts()[:10]

The three most common dog ratings (ignoring the denominator) were 12, 10 and 11.

Which was the most common dog name in the dataset?

In [ ]:
twitter_archive_master['name'].value_counts()[:10]

Charlie was the most common dog name with 11 appearences in the dataset, followed by Oliver, Cooper and Lucy (10 times each).

How many original tweets were posted per month?

In [ ]:
twitter_archive_master.groupby(['Month', 'Year'], 
                               sort=False).count().iloc[::-1, 0]

In [ ]:
tweets_per_month = twitter_archive_master.groupby(['Month', 'Year'], 
                               sort=False).count().iloc[::-1, 0]

In [ ]:
fig, ax = plt.subplots()
sns.set_style("white")
tweets_per_month.plot(kind='bar', color='b')
ax.set_title('Number of original tweets per month', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
ax.set_xlabel('')
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

November and December of 2015 were the most busy months for WeRateDogs twitter account with the number of original posted tweets exceeding 250 and 350 respectively. From April 2016 and onwards no month had more than 100 tweets posted.

In which day of the week WeRateDogs posted most of its original tweets?

In [ ]:
sort_of_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday', 'Saturday']

plotting_days = pd.DataFrame(twitter_archive_master.groupby('Day_of_Week')['tweet_id'].count())

plotting_days.reset_index(inplace=True)
plotting_days = plotting_days.rename(columns={'tweet_id': 'count'})

plotting_days['Day_of_Week'] = plotting_days.Day_of_Week.astype("category")

plotting_days.Day_of_Week.cat.set_categories(sort_of_days, inplace=True)

plotting_days = plotting_days.sort_values('Day_of_Week')

plotting_days

In [ ]:
fig, ax = plt.subplots()
sns.set_style("white")
sns.barplot(x="Day_of_Week", y="count", data=plotting_days, color='g')
ax.set_title('Number of original tweets per day', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
plt.xticks(rotation='horizontal')
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

It seems that WeRateDogs was more active on Mondays and less active on Saturdays. There is a decreasing trend in the number of tweets posted as we approach the end of the week.

In which hour of the day WeRateDogs posted most of its original tweets?

In [ ]:
twitter_archive_master['Hour'].value_counts()

In [ ]:
fig, ax = plt.subplots()
twitter_archive_master['Hour'].value_counts(sort=False).plot(kind='bar')
ax.set_title('Number of original tweets per time of the day', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
ax.set_xlabel('Time of the day', fontsize=12)
plt.xticks(rotation='horizontal') 
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

Most tweets were posted between midnight and 3 a.m. In general the account holder of WeRateDogs seems to be active from 3 p.m. until 5 a.m. every day.

Which was the most used Twitter app to post tweets by WeRateDogs?

In [ ]:
twitter_archive_master['source'].value_counts() / len(twitter_archive_master) * 100

WeRateDogs moderator clearly prefers tweeting from an iPhone (98% of the time)

For how many dogs a dog 'stage' is available?

In [ ]:
twitter_archive_master['stage'].value_counts()/len(twitter_archive_master) * 100


Most dogs don't have a dog 'stage' (84%). More than 1 out of 10 dogs are identified as puppers (usually a younger dog).

For how many dog breed predictions the trained neural net was most confident?

In [ ]:
twitter_archive_master[twitter_archive_master['top_pred_conf'] == 1]

For only one dog prediction the neural net was confident 100% for its accuracy. It predicted that there is no dog in the tweet image, instead a prayer rug is depicted. The algorithm clearly missed the dog and it was probably confused by the puzzle.

Which tweet was the most retweeted one in the dataset?

In [ ]:
twitter_archive_master[twitter_archive_master['retweet_count'] == max(twitter_archive_master['retweet_count'])]

The most retweeted tweet was this one: https://t.co/7wE9LTEXC4 It shows a dog in a pool 